# Generated by Django 5.2.14 on 2026-06-08 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome do curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20, verbose_name='Dia da semana')),
                ('hora_inicio', models.TimeField(verbose_name='Horário de inicio')),
                ('hora_fim', models.TimeField(verbose_name='Horário de fim')),
            ],
            options={
                'verbose_name': 'Horário',
                'verbose_name_plural': 'Horários',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, verbose_name='Nome da ocupação')),
                ('pode_reservar', models.BooleanField(verbose_name='Pode reservar')),
                ('precisa_aprovacao', models.BooleanField(verbose_name='Precisa de aprovação')),
            ],
            options={
                'verbose_name': 'Ocupção',
                'verbose_name_plural': 'Ocupações',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número da sala')),
                ('predio', models.CharField(max_length=30, verbose_name='Prédio')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade (pessoas)')),
                ('ativa', models.BooleanField(default=True, verbose_name='Sala ativa')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='StatusReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Status da reserva')),
            ],
            options={
                'verbose_name': 'Status da reserva',
                'verbose_name_plural': 'Status das reservas',
            },
        ),
        migrations.CreateModel(
            name='TipoConflito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de conflito')),
            ],
            options={
                'verbose_name': 'Tipo de conflito',
                'verbose_name_plural': 'Tipos de conflito',
            },
        ),
        migrations.CreateModel(
            name='TipoConservacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conservacao', models.CharField(max_length=30, verbose_name='Conservação')),
                ('prioridade_manutencao', models.CharField(max_length=6, verbose_name='Nível de prioridade')),
            ],
            options={
                'verbose_name': 'Conservação',
                'verbose_name_plural': 'Conservações',
            },
        ),
        migrations.CreateModel(
            name='TipoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sala', models.CharField(max_length=50, verbose_name='Tipo da sala')),
            ],
            options={
                'verbose_name': 'Tipo de Sala',
                'verbose_name_plural': 'Tipos de Sala',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da pessoa')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='AlocacaoProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField(verbose_name='Ano letivo')),
                ('semestre_letivo', models.IntegerField(verbose_name='Semestre letivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplina', verbose_name='Disciplina')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Nome da pessoa')),
            ],
            options={
                'verbose_name': 'Alocação',
                'verbose_name_plural': 'Alocações',
            },
        ),
        migrations.CreateModel(
            name='ReservaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alocacao_professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alocacaoprofessor', verbose_name='Alocação do professor')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horario', verbose_name='Horário')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoa', verbose_name='Pessoa')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala', verbose_name='Sala')),
                ('status_reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.statusreserva', verbose_name='Status da reserva')),
            ],
            options={
                'verbose_name': 'Reserva de sala',
                'verbose_name_plural': 'Reservas de salas',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_software', models.CharField(max_length=50, verbose_name='Nome do software')),
                ('versao', models.CharField(max_length=15, verbose_name='Versão do software')),
                ('sistema_operacional', models.CharField(max_length=30, verbose_name='Sistema operacional')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Software por laboratório',
                'verbose_name_plural': 'Softwares por laboratório',
            },
        ),
        migrations.CreateModel(
            name='ConflitoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80, verbose_name='Descrição do conflito')),
                ('resolvido', models.BooleanField(default=False, verbose_name='Resolvido')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reservasala', verbose_name='Reserva')),
                ('tipo_conflito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoconflito', verbose_name='Tipo de conflito')),
            ],
            options={
                'verbose_name': 'Conflito de reserva',
                'verbose_name_plural': 'Conflitos de reservas',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipamento', models.CharField(default='Sem nome', max_length=50, verbose_name='Nome do equipamento')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de equipamentos')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala', verbose_name='Sala')),
                ('tipo_conservacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tipoconservacao', verbose_name='Estado da conservação')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
        migrations.AddField(
            model_name='sala',
            name='tipo_sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiposala', verbose_name='Tipo da sala'),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turma', models.CharField(max_length=10, verbose_name='Turma')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AddField(
            model_name='reservasala',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
        migrations.AddField(
            model_name='alocacaoprofessor',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.turma', verbose_name='Turma'),
        ),
    ]
